const sampleData = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: '123456',
      role: 'admin',
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: '123456',
      role: 'user',
    },
  ],
  products: [
    {
      name: 'Elegant Evening Gown',
      slug: 'elegant-evening-gown',
      category: "Women's Dresses",
      description: 'A stunning gown perfect for evening events',
      images: [
        '/images/sample-products/w1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 199.99,
      brand: 'Versace',
      rating: 4.8,
      numReviews: 15,
      stock: 3,
      isFeatured: true,
      banner: 'banner-1.jpg',
    },
    {
      name: 'Chic Cocktail Dress',
      slug: 'chic-cocktail-dress',
      category: "Women's Dresses",
      description: 'A chic dress for cocktail parties',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 129.99,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: 'banner-2.jpg',
    },
    {
      name: 'Stylish Handbag',
      slug: 'stylish-handbag',
      category: "Women's Accessories",
      description: 'A stylish handbag to complement any outfit',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 89.95,
      brand: 'Prada',
      rating: 4.9,
      numReviews: 8,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Luxury Silk Scarf',
      slug: 'luxury-silk-scarf',
      category: "Women's Accessories",
      description: 'A luxurious silk scarf for a touch of elegance',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 59.95,
      brand: 'Hermès',
      rating: 4.7,
      numReviews: 12,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Designer Sunglasses',
      slug: 'designer-sunglasses',
      category: "Women's Accessories",
      description: 'Stylish sunglasses for a fashionable look',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 149.99,
      brand: 'Chanel',
      rating: 4.6,
      numReviews: 20,
      stock: 4,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Elegant Pearl Necklace',
      slug: 'elegant-pearl-necklace',
      category: "Women's Accessories",
      description: 'An elegant pearl necklace for special occasions',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 299.99,
      brand: 'Tiffany & Co.',
      rating: 4.9,
      numReviews: 25,
      stock: 2,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
